from enum import Enum

class AllureTags(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    REGRESSIONS = "REGRESSIONS"
    NAVIGATION = "NAVIGATION"
    REGISTRATIONS = "REGISTRATIONS"
    AUTHORIZATION = "AUTHORIZATION"